version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/pulpfiction
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv ~/venv
            . ~/venv/bin/activate
            python setup.py dev
      - run:
          name: lint
          command: |
            . ~/venv/bin/activate
            flake8 .
  deploy:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/pulpfiction
    steps:
      - checkout
      - run:
          name: install deploy dependencies
          command: |
            python3 -m venv ~/venv
            . ~/venv/bin/activate
            pip install twine
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = ${PYPY_USER}" >> ~/.pypirc
            echo -e "password = ${PYPI_PASSWORD}" >> ~/.pypirc
      - run:
          name: push to PyPI
          command: |
            python setup.py sdist
            python setup.py bdist_wheel
            . ~/venv/bin/activate
            twine upload dist/*

workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
