version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/tinyfn
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv ~/venv
            . ~/venv/bin/activate
            python setup.py dev
      - run:
          name: run tests
          command: |
            . ~/venv/bin/activate
            flake8 .
